// <auto-generated>

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements should appear in the correct order", Justification = "<En attente>", Scope = "member", Target = "~M:EducationalTeamsBotApi.Domain.Entities.CosmosReaction.#ctor(System.String,System.String,System.Int32)")]
